### ISSUE TITLE
token logging page is error

### ISSUE THREAD

**Issue by a1141539455** [MRCIEU/ieugwasr#101]
![屏幕截图 2024-07-29 085245](https://github.com/user-attachments/assets/1a8c35da-c6b0-4440-97ab-91883639829b)
https://mrcieu.github.io/ieugwasr/articles/guide.html#authentication. 
When you log in to your account, an error message appears

**Comment by JasonQiu** [comment]
Please clear your browser cache. If problem persists, provide the address shown in the address bar. Which method (Microsoft, GitHub, Email verification) did you use?

**Comment by a1141539455** [comment]
problem persists
I used the Microsoft.
https://api.opengwas.io/profile/auth/microsoft/redirect?code=M.C513_BAY.2.U.b97d55a6-28bb-91fd-72a4-36713a3d5153&client_info=eyJ2ZXIiOiIxLjAiLCJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFEXzJhak44WExtbnBIZlFDbHIyU2dBIiwibmFtZSI6Imp1bnhpbmcgbGkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiIxMTQxNTM5NDU1QHFxLmNvbSIsIm9pZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC00MWFlLThjODA1NTlkZjA1OCIsInRpZCI6IjkxODgwNDBkLTZjNjctNGM1Yi1iMTEyLTM2YTMwNGI2NmRhZCIsImhvbWVfb2lkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTQxYWUtOGM4MDU1OWRmMDU4IiwidWlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTQxYWUtOGM4MDU1OWRmMDU4IiwidXRpZCI6IjkxODgwNDBkLTZjNjctNGM1Yi1iMTEyLTM2YTMwNGI2NmRhZCJ9&state=vgRwxecLbsnEhUFJ

**Comment by a1141539455** [comment]
All verification methods have the above problems. T_T

**Comment by JasonQiu** [comment]
Please try again.
