### ISSUE TITLE
Using the new API but still cannot do ld_clump

### ISSUE THREAD

**Issue by Gong21** [MRCIEU/ieugwasr#102]
Several members of our group, including myself, are facing the following issue. We have recently started using the new API (https://api.opengwas.io/api/). We followed all the steps to get our tokens authenticated. Running ieugwasr::user() returned our user info.

However, when we ran ieugwasr::ld_clump, either all of the variants were removed, or we received this error "Error in mtfrm.default(list(url = "http://gwas-api.mrcieu.ac.uk/ld/clump", : cannot mtfrm". How do we fix this? 

This issue started on 22 July and persisted. We don't think it is related to our allowance, since one of our members is a new user and he received this error for his first attempt.

**Comment by JasonQiu** [comment]
Please provide a _**full, minimal and reproducible**_ example (the variant and a series of commands).

**Comment by Gong21** [comment]
[SNP_list.csv](https://github.com/user-attachments/files/16456944/SNP_list.csv)

ieugwasr::user() #user info was displayed

#Attempt 1.
SNP_list <- read.csv(file="SNP_list.csv")
data.clump = ieugwasr::ld_clump(SNP_list)

#message obtained: 
#Clumping gXarfk, 125577 variants, using EUR population reference
#Removing 125577 of 125577 variants due to LD with other variants or absence from LD reference panel

#my colleague received this message:
#"Error in mtfrm.default(list(url = "http://gwas-api.mrcieu.ac.uk/ld/clump", : cannot mtfrm"

#Attempt 2.
data.clump2 <- ieugwasr::ld_clump(dplyr::tibble(rsid=SNP_list$rsid, pval=SNP_list$pval))
#same messages as above

Thanks for your help!

**Comment by JasonQiu** [comment]
If `ieugwasr::user()` works then it must be calling api.opengwas.io as it should be. Did you switched to `gwas-api.mrcieu.ac.uk` (now deprecated) at some point?

**Comment by JasonQiu** [comment]
120k variants are too many. Once you are sure you are using api.opengwas.io (see below), could you only keep a few (< 10) variants and try again?

Expected output:
```
> options('ieugwasr_api')
$ieugwasr_api
[1] "https://api.opengwas.io/api/"
```

**Comment by JasonQiu** [comment]
1. Make sure you are using api.opengwas.io (this is the default value used by the latest versions of ieugwasr and TwoSampleMR - considering upgrading if you haven't) and forget about any command that contains gwas-api.mrcieu.ac.uk
2. Considering running local Ld operations https://mrcieu.github.io/ieugwasr/articles/local_ld.html

**Comment by Gong21** [comment]
We have been trying to use api.opengwas.io since July, and as far as we are aware, we didn't switch back to gwas-api.mrcieu.ac.uk since then (at least not intentionally).

This is our output:
> options('ieugwasr_api')
$ieugwasr_api
[1] "https://api.opengwas.io/api/"

**Comment by Gong21** [comment]
> 120k variants are too many. Once you are sure you are using api.opengwas.io (see below), could you only keep a few (< 10) variants and try again?
> 
> Expected output:
> 
> ```
> > options('ieugwasr_api')
> $ieugwasr_api
> [1] "https://api.opengwas.io/api/"
> ```
Hi Jason, it worked for 10 SNPs. What is the limit to the number of SNPs we can include when using api.opengwas.io ? Would it be possible to increase this limit ? 

We have tried clumping locally, but that was not the solution, because the list of SNPs generated from local-clumping and server-clumping is different enough to lead to considerable differences in MR associations. This is important because we need to replicate previous analyses that used server-clumped SNPs.

We have followed all the steps to ensure our local clumping was done correctly. The servers we have tried were gwas-api.mrcieu.ac.uk (in 2023), and api.opengwas.io (it worked for 1-2 hours in July 2024).

**Comment by JasonQiu** [comment]
> Please provide a _**full, minimal and reproducible**_ example (the variant and a series of commands).

@Zhanjiajun 
Please provide a **_full, minimal and reproducible_** example (the variant and a series of commands). Note the variants list must be minimal i.e. to trigger the error not variant can be removed further from the list.

**Comment by JasonQiu** [comment]
> I had met a similar problem, all of variants were removed removed "due to LD with other variants or absence from LD reference panel" despite the number of variants of any GWAS summary dataset.

@Zhanjiajun
Please provide a **_full, minimal and reproducible_** example (the variant and a series of commands). Note the variants list must be minimal i.e. to trigger the error no variant can be removed further from the list.
