### ISSUE TITLE
I have my access token but R or the server is not letting me access the ieugwas server

### ISSUE THREAD

**Issue by erthrall** [MRCIEU/ieugwasr#105]
Whilst I was trying to rerun some analyses, 

```
outcome <- extract_outcome_data(snps=SNPs, 
                                            outcomes = 'ebi-a-GCST90018974',
                                            proxies = F)
```
The following error occurred:
> Extracting data for 148 SNP(s) from 1 GWAS(s)
> Error in ieugwasr::associations(variants = snps, id = outcomes, proxies = proxies,  : 
>   unused argument (access_token = access_token)

This is strange because I never had any problems with access tokens before when I used the package to access data..

I then found my way to the link below and tried the steps in the tutorial.
[https://mrcieu.github.io/ieugwasr/articles/guide.html#authentication](https://mrcieu.github.io/ieugwasr/articles/guide.html#authentication)

However, even after following the steps, I still could not call `extract_outcome_data`. This is puzzling because the two checkpoints in the tutorial returned the desired outcome:

>To check that your token is being recognised, run `ieugwasr::get_opengwas_jwt()`. If it returns a long random string then you are authenticated.

`get_opengwas_jwt()` returned my access token. This means that I "am authenticated".

>To check that your token is working, run `user()`. It will make a request to the API for your user information using your token. It should return a list with your user information. If it returns an error, then your token is not working.

`user()` returned a list of my user information, meaning my token worked.

Kindly advise.

**Comment by JasonQiu** [comment]
Please check your ieugwasr and TwoSampleMR versions. Try to [detach](https://stackoverflow.com/questions/6979917/how-to-unload-a-package-without-restarting-r), remove, install the latest versions (1.0.1 and 0.6.7 respectively) and load again.
