### ISSUE TITLE
Getting an error while fetching data for a trait of interest

### ISSUE THREAD

**Issue by Bhashitha2014** [MRCIEU/ieugwasr#108]
Getting an error while fetching the data for a trait of interest as mentioned below, even after updating the ieugwasr and TwoSampleMR packages.

<img width="550" alt="image" src="https://github.com/user-attachments/assets/60590357-1898-4d69-a8a9-7884d38635e9">

Any help in this regard will be greatly appreciated.

Thanks!

**Comment by JasonQiu** [comment]
#89
