### ISSUE TITLE
Is the IEU API server down?

### ISSUE THREAD

**Issue by szhang99-bu** [MRCIEU/ieugwasr#110]
Is the IEU API server down for maintenance? Where can I get update or newsletter regarding the maintenance scheduled?

```
> ieugwasr::api_status()
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server error: 503
Failed to retrieve results from server. See error status message in the returned object and contact the developers if the problem persists.
                          url: http://gwas-api.mrcieu.ac.uk/status 
                  status_code: 503 
                      headers: Error in cat(format(paste0(y, ":"), width = 30, justify = "right"), x[[y]],  : 
  argument 2 (type 'list') cannot be handled by 'cat'

> ieugwasr::user()
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server error: 503
Failed to retrieve results from server. See error status message in the returned object and contact the developers if the problem persists.
Response [http://gwas-api.mrcieu.ac.uk/user]
  Date: 2024-12-11 15:52
  Status: 503
  Content-Type: text/html; charset=iso-8859-1
  Size: 299 B
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>
```

**Comment by Ali-mhm** [comment]
> Is the IEU API server down for maintenance? Where can I get update or newsletter regarding the maintenance scheduled?
> 
> ```
> > ieugwasr::api_status()
> Server code: 503; Server is possibly experiencing traffic, trying again...
> Server code: 503; Server is possibly experiencing traffic, trying again...
> Server code: 503; Server is possibly experiencing traffic, trying again...
> Server code: 503; Server is possibly experiencing traffic, trying again...
> Server code: 503; Server is possibly experiencing traffic, trying again...
> Server code: 503; Server is possibly experiencing traffic, trying again...
> Server error: 503
> Failed to retrieve results from server. See error status message in the returned object and contact the developers if the problem persists.
>                           url: http://gwas-api.mrcieu.ac.uk/status 
>                   status_code: 503 
>                       headers: Error in cat(format(paste0(y, ":"), width = 30, justify = "right"), x[[y]],  : 
>   argument 2 (type 'list') cannot be handled by 'cat'
> 
> > ieugwasr::user()
> Server code: 503; Server is possibly experiencing traffic, trying again...
> Server code: 503; Server is possibly experiencing traffic, trying again...
> Server code: 503; Server is possibly experiencing traffic, trying again...
> Server code: 503; Server is possibly experiencing traffic, trying again...
> Server code: 503; Server is possibly experiencing traffic, trying again...
> Server code: 503; Server is possibly experiencing traffic, trying again...
> Server error: 503
> Failed to retrieve results from server. See error status message in the returned object and contact the developers if the problem persists.
> Response [http://gwas-api.mrcieu.ac.uk/user]
>   Date: 2024-12-11 15:52
>   Status: 503
>   Content-Type: text/html; charset=iso-8859-1
>   Size: 299 B
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>503 Service Unavailable</title>
> </head><body>
> <h1>Service Unavailable</h1>
> <p>The server is temporarily unable to service your
> request due to maintenance downtime or capacity
> problems. Please try again later.</p>
> </body></html>
> ```

I am experiencing the same issue.

**Comment by Ali-mhm** [comment]
To access the OpenGWAS API, follow these steps:
1. Create an account at [OpenGWAS](https://api.opengwas.io/?next=%2Fprofile%2F).
2. Upgrade to the normal plan, which allows 100,000 queries every 10 minutes.
3. Obtain a JSON Web Token (JWT) valid for 14 days. This token acts like a password for server access.
4. 
**To set your token in R, follow these steps:**

1. Add your token to the `.Renviron` file: Add the line `OPENGWAS_JWT=<token>` to your `.Renviron` file. This file can be located either in your home directory or in the working directory of your R session.

2. Check the location of your `.Renviron` file: You can check the location of your `.Renviron` file by running the following command in R
```
Sys.getenv("R_ENVIRON_USER")
```
If there is no `.Renviron` file in your R environment, you can create one using the `usethis` package in R. 
```
install.packages("usethis")
library(usethis)
```
Create a `.Renviron`
```
usethis::edit_r_environ() 
```
3. Save and close the .Renviron file.

4. Restart your R session to apply the changes.
5. Verify the token by running the following commands:
```
# Check if the token is recognized
token_check <- ieugwasr::get_opengwas_jwt()
print(token_check)  # Should print a long random string if authenticated

# Check if the token is working
user_info <- user()
print(user_info)  # Should print a list with your user information
```
**_Notes:_**

> Replace <your_token_here> with your actual token.

> If the .Renviron file already exists, usethis::edit_r_environ() will open it for editing.

> Always restart your R session after modifying the .Renviron file to ensure the changes take effect_

**Comment by daisy-78** [comment]
I am already the standard user, but "Server code: 503" still occurs while retrieving exposure/outcomes.  It occurs from time to time. I suspect it's unstable.

**Comment by JasonQiu** [comment]
> I am already the standard user, but "Server code: 503" still occurs while retrieving exposure/outcomes. It occurs from time to time. I suspect it's unstable.

Please paste the entire list of commands you used so that we can reproduce

**Comment by JasonQiu** [comment]
No need to run `options()` to change the API base URL - that is not a standard practice and is not in the documentation. Also please make sure you are running the latest versions of ieugwasr and TwoSampleMR.

**Comment by ssxxmmm** [comment]
I've also encountered this problem, and it's been showing these messages for several days now, consistently.I am already the standard user，and I've also updated the token.
> library(ieugwasr)
> api_status()
                  API version: 4.0.0 
                       Access: public 
                        Neo4j: Available 
                ElasticSearch: Available 
                      Airflow: Available 
                       PheWAS: Unavailable 
           LD reference panel: Available 
  1000 genomes annotation VCF: Available 
             PLINK executable: Available 
           Total associations: 346926210464 
      Total complete datasets: 50197 
        Total public datasets: 
> options(ieugwasr_api = 'gwas-api.mrcieu.ac.uk/')
> api_status()
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server error: 503
Failed to retrieve results from server. See error status message in the returned object and contact the developers if the problem persists.
                          url: http://gwas-api.mrcieu.ac.uk/status 
                  status_code: 503 
                      headers: Error in cat(format(paste0(y, ":"), width = 30, justify = "right"), x[[y]],  :

**Comment by JasonQiu** [comment]
> I've also encountered this problem, and it's been showing these messages for several days now, consistently.I am already the standard user，and I've also updated the token.
> 
> > library(ieugwasr)
> > api_status()
> > API version: 4.0.0
> > Access: public
> > Neo4j: Available
> > ElasticSearch: Available
> > Airflow: Available
> > PheWAS: Unavailable
> > LD reference panel: Available
> > 1000 genomes annotation VCF: Available
> > PLINK executable: Available
> > Total associations: 346926210464
> > Total complete datasets: 50197
> > Total public datasets:
> > options(ieugwasr_api = 'gwas-api.mrcieu.ac.uk/')
> > api_status()
> > Server code: 503; Server is possibly experiencing traffic, trying again...
> > Server code: 503; Server is possibly experiencing traffic, trying again...
> > Server code: 503; Server is possibly experiencing traffic, trying again...
> > Server code: 503; Server is possibly experiencing traffic, trying again...
> > Server code: 503; Server is possibly experiencing traffic, trying again...
> > Server code: 503; Server is possibly experiencing traffic, trying again...
> > Server error: 503
> > Failed to retrieve results from server. See error status message in the returned object and contact the developers if the problem persists.
> > url: http://gwas-api.mrcieu.ac.uk/status
> > status_code: 503
> > headers: Error in cat(format(paste0(y, ":"), width = 30, justify = "right"), x[[y]],  :

https://github.com/MRCIEU/ieugwasr/issues/110#issuecomment-2545322827

**Comment by Coco-Zhaozhao** [comment]
Hi, there, how did you solve this error
