### ISSUE TITLE
Why can't the IEU API be used anymore? Is the IEU API server down?

### ISSUE THREAD

**Issue by ssxxmmm** [MRCIEU/ieugwasr#111]
running the code to obtain IEU information has always resulted in an error. Failed to retrieve results from server.Is the IEU API server down for maintenance? I really need help！！！😭

> exp_dat <- extract_instruments(
+   outcomes=exp_dat_id$id,
+   p1 = 5e-08,
+   clump = TRUE,
+   p2 = 5e-08,
+   r2 = 0.001,
+   kb = 10000,
+   opengwas_jwt = ieugwasr::get_opengwas_jwt(),
+   force_server = FALSE
+ )
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server error: 503
Failed to retrieve results from server. See error status message in the returned object and contact the developers if the problem persists.
Error in if (nrow(d) == 0) return(NULL) :

**Comment by JasonQiu** [comment]
https://github.com/MRCIEU/ieugwasr/issues/110#issuecomment-2545322827
