### ISSUE TITLE
How to just pull full summary statistics? E.g. as input for LDSC

### ISSUE THREAD

**Issue by NathanSkene** [MRCIEU/ieugwasr#13]
Would really appreciate any tips on how to do this! Basically what I want is to be able to pull a data frame which has:

- SNP, CHR, BP as first three columns.
- At least one of these columns: (“Z”,“OR”,“BETA”,“LOG_ODDS”,“SIGNED_SUMSTAT”)
- All of these columns: (“SNP”,“CHR”,“BP”,“P”,“A1”,“A2”)

For every SNP tested in a given GWAS with MAF > 0.01 and INFO > 0.9

Thanks

**Comment by t0mrg** [comment]
See [gwasvcf](https://github.com/MRCIEU/gwasvcf).

We _don't_ recommend using the R package or API for pulling the full summary statistics, as it is computationally inefficient. Instead you can just download the full datasets here: [https://gwas.mrcieu.ac.uk/](https://gwas.mrcieu.ac.uk/).

The URL structure is consistent (eg for ID ```ebi-a-GCST006414``` the link is [https://gwas.mrcieu.ac.uk/files/ebi-a-GCST006414/ebi-a-GCST006414.vcf.gz](https://gwas.mrcieu.ac.uk/files/ebi-a-GCST006414/ebi-a-GCST006414.vcf.gz))

You can then use the [gwasvcf](https://github.com/MRCIEU/gwasvcf) R package to extract the data.
