### ISSUE TITLE
Error: Failed to install 'ieugwasr' from GitHub:

### ISSUE THREAD

**Issue by syywong** [MRCIEU/ieugwasr#14]
I tried to install 'ieugwasr' using the following code in R Studio:

devtools::install_github("mrcieu/ieugwasr")

After having specified that I want to update all associated packages, I receive the following warning message:
Error in file.rename(instdir, final_instdir)：
(converted from warning) cannot rename file 'C:/Users/Vincent/Documents/R/win-library/4.0/00LOCK-fansi/00new/fansi" to 'C://Users/vincent/Documents/R/win-library/4.0/fansi', reason '????'
* removing 'C:/Users/vincent/Documents/R/win-library/4.0/fansi'
Error: Failed to install 'ieugwasr' from GitHub:
(converted from warning) installation of package ‘fansi’ had non-zero exit status

I have tried to run the code with RStudio (R version 4.0.3).

May I know how I could solve this error? Thanks in advance!

**Comment by remlapmot** [comment]
Closing as this is an old issue and no longer a problem.
