### ISSUE TITLE
Error: Could not authenticate via any gargle cred function

### ISSUE THREAD

**Issue by showers14** [MRCIEU/ieugwasr#35]
hello 
i run command" ieugwasr::get_access_token()"

Using access token. For info on how this is used see logging_info()
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error: Could not authenticate via any gargle cred function

how to fix this problem?
 thank you

**Comment by Hugolyu** [comment]
Hi @showers14 
 I encountered the same program error problem as you; have you ever solved it now? Could you share your experience solving it?
Thank you very much.

**Comment by explodecomputer** [comment]
Do you need to authenticate? That's only required to access specific private datasets to which you have been granted access. If not, delete the folder called `ieugwasr_oauth` in your directory, you don't need to run `get_access_token()`.

If you need access to a private dataset let me know

**Comment by Hugolyu** [comment]
Thanks to your advice, I deleted the `ieugwasr_oauth` folder and I don't need the private token anymore. I really appreciate your help!
