### ISSUE TITLE
Error: Warning: No significant --clump results.  Skipping.

### ISSUE THREAD

**Issue by JonnyBaseball** [MRCIEU/ieugwasr#36]
I am using ieugwasr ld_clump local; error for only some files.  

dat011 <- subset(dat01, dat01$mr_keep != FALSE)
    dat02<- dat011[!duplicated(dat011$SNP),]
    dat02$rsid <- dat02$SNP
    dat02$pval <- dat02$pval.exposure
    dat02$id <- dat02$id.exposure
    
    dat0 <- ld_clump(dat=dat02, # variant, pval, id - won't work with SNP, pval.exposure or id.exposure
                     clump_kb=250,
                     clump_r2=0.2,
                     clump_p=.1,
                     plink_bin = genetics.binaRies::get_plink_binary(),
                     bfile = "/users/DXXXX/Desktop/LDREF/EUR"
    )
    

Looping from csv files in R version 4.2.0, here is 1 file that returned the error (only 10 of 1500 returned the error)

rsid | pval | id
rs117276717 | 6.76E-130 | C1S
rs12146727 | 5.00E-305 | C1S

The SNPs are present in 1000G Phase 3.  

Why the error?  I would try the handful on the server, but the server is experiencing traffic.

Thanks for any help you can give me in this.  

#### 
Clumping C1S, 2 variants, using EUR population reference
PLINK v1.90b6.21 64-bit (19 Oct 2020)          www.cog-genomics.org/plink/1.9/
(C) 2005-2020 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to /var/folders/rl/6vqvm_h5319fml5s4vw8fbfr0000gn/T//RtmpUwLPve/filecb1a3f8e9162.log.
Options in effect:
  --bfile /users/DXXX/Desktop/LDREF/EUR
  --clump /var/folders/rl/6vqvm_h5319fml5s4vw8fbfr0000gn/T//RtmpUwLPve/filecb1a3f8e9162
  --clump-kb 250
  --clump-p1 1
  --clump-r2 0.2
  --out /var/folders/rl/6vqvm_h5319fml5s4vw8fbfr0000gn/T//RtmpUwLPve/filecb1a3f8e9162

65536 MB RAM detected; reserving 32768 MB for main workspace.
8550156 variants loaded from .bim file.
503 people (0 males, 0 females, 503 ambiguous) loaded from .fam.
Ambiguous sex IDs written to
/var/folders/rl/6vqvm_h5319fml5s4vw8fbfr0000gn/T//RtmpUwLPve/filecb1a3f8e9162.nosex
.
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 503 founders and 0 nonfounders present.
Calculating allele frequencies... done.
8550156 variants and 503 people pass filters and QC.
Note: No phenotypes present.
Warning: No significant --clump results.  Skipping.

Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/var/folders/rl/6vqvm_h5319fml5s4vw8fbfr0000gn/T//RtmpUwLPve/filecb1a3f8e9162.clumped': No such file or directory

**Comment by JonnyBaseball** [comment]
I think I have answered my own question - this is error when rsid's are not found in Reference 1000G file.  My own example - the snps were actually not in the Reference 1000G file when I searched again one by one.

**Comment by XjtuZhangKun-lab** [comment]
Hi, so how do you fix this?
