### ISSUE TITLE
 Issue with available_outcomes() in ieugwasr Package: Error Accessing status_code

### ISSUE THREAD

**Issue by JACKDDDDDDDDDDDD** [MRCIEU/ieugwasr#55]
Hello,

I've encountered an issue while using the `ieugwasr` package, specifically with the `available_outcomes()` function. When I call this function, I receive an error related to accessing the `status_code` of an atomic vector, which suggests that the expected HTTP response object might not be correctly handled or returned as expected.

**Error Message:
Error in r$status_code : $ operator is invalid for atomic vectors

The traceback suggests that the error originates from the `api_query("gwasinfo", access_token = access_token)` call within the `ieugwasr::gwasinfo` function.

**Steps to Reproduce:**
1. Load the `ieugwasr` package.
2. Attempt to call `available_outcomes()`.

**Environment:**
- R version: (4.3.3)
- `ieugwasr` package version: (0.1.0)
- Operating System: (windows11

I'm wondering if anyone else has encountered this issue or if there's a known solution or workaround. Any insights or suggestions on how to address this problem would be greatly appreciated.

Thank you for your time and help.

Best regards

**Comment by explodecomputer** [comment]
Thanks for this. New commit should fix this, please reinstall ieugwasr f1d6d238fb86576bc431c3acd0cb7d9e9df10d3a
