### ISSUE TITLE
Only send requests when there is remaining allowance

### ISSUE THREAD

**Issue by JasonQiu** [MRCIEU/ieugwasr#71]
When `status_code == 429`:
- display the information of `X-Allowance-Limit`, `X-Allowance-Remaining`, `X-Allowance-Reset` and `Retry-After` in the response headers in a user-friendly way if possible
- cache the `X-Allowance-Reset` value

https://github.com/MRCIEU/ieugwasr/blob/127d1ea5a6ead6fa6c037dcc44ec77d39f952f21/R/query.R#L80

Before a request can be sent, always check whether a (cached) `X-Allowance-Reset` is present
- If not, proceed with the request
- If yes but the time indicated is still in the future, do not send the request (might be good if users can ignore this using a parameter, though at their own risk)
- If yes and the time has passed, clear the cached value and proceed with the request

https://github.com/MRCIEU/ieugwasr/blob/127d1ea5a6ead6fa6c037dcc44ec77d39f952f21/R/query.R#L37

In this way, users can leave the program running, and it will work only when it knows that there is allowance remaining. Without this, users may accumulate too many 429 errors unconsciously in a short period of time and result in their IP address being banned by the gateway.

**Comment by wula-pro** [comment]
The ip address is always displayed when it is blocked:   #Error in api_query("user", opengwas_jwt = opengwas_jwt) : 
  The query to MR-Base exceeded 300 seconds and timed out. Please simplify the query

**Comment by wula-pro** [comment]
Hello, I would like to ask you how many errors more than that will get me banned?

**Comment by JasonQiu** [comment]
> Hello, I would like to ask you how many errors more than that will get me banned?

If you get the 429 error and keep making requests, your IP could be banned at anytime.

**Comment by JasonQiu** [comment]
I have implemented this in https://github.com/MRCIEU/ieugwaspy/commit/ac92f96f58604a8ae4f09d1e4cf077afb181ad67, @explodecomputer do you think if ieugwasr could also benefit from this? Thanks!

**Comment by wula-pro** [comment]
```r
while(TRUE){
  message_to_next <<- TRUE
  error_to_next <<- FALSE
  try({withCallingHandlers(exp_clumped<-clump_data(exp), 
                           message = function(c) if (stringr::str_detect(as.character(c),"Failed to")) message_to_next <<- FALSE)
    error_to_next <<- TRUE})
  if(message_to_next == TRUE&error_to_next == TRUE) { break }
}

}else{
  while(TRUE){
    message_to_next <<- TRUE
    error_to_next <<- FALSE
    try({withCallingHandlers(exp_clumped<-extract_instruments(outcomes = id,p1 = 5e-08), 
                             message = function(c) if (stringr::str_detect(as.character(c),"Failed to")) message_to_next <<- FALSE)
      error_to_next <<- TRUE})
    if(message_to_next == TRUE&error_to_next == TRUE) { break }
  }
``` Some expose will have failed to fetch the snp and the ip will be blocked when I continue to request it

**Comment by explodecomputer** [comment]
need to convert timezone e.g. `ymd_hms(as.POSIXct(val, origin="1970-01-01"), tz=Sys.timezone())`

**Comment by erkangYi** [comment]
I hope this message finds you. I am writing to express my sincerest apologies for submitting too many requests in a short period of time, causing your server to become overloaded recently. Initially, I was concerned that a potential network problem might prevent further connections, prompting me to send multiple queries in quick succession. Here is my ip address: 192.168.1.4. I hope you can help unblock it, thank you!
