### ISSUE TITLE
The ip address is always displayed when it is blocked:

### ISSUE THREAD

**Issue by wula-pro** [MRCIEU/ieugwasr#72]
![image](https://github.com/MRCIEU/ieugwasr/assets/145174952/b18f990a-ab2c-43fb-9faa-9f622d6b03c5)

**Comment by JasonQiu** [comment]
Please check your remaining allowance at https://api.opengwas.io/profile/

**Comment by wula-pro** [comment]
I hope this message finds you. I am writing to express my sincerest apologies for submitting too many requests in a short period of time, causing your server to become overloaded recently. Initially, I was concerned that a potential network problem might prevent further connections, prompting me to send multiple queries in quick succession. Here is my ip address: 175.43.121.206. I hope you can help unblock it, thank you!

> 请在 https://api.opengwas.io/profile/ 检查您的剩余限额
> 
> 另请注意 [#69 中的最后一段（评论）](https://github.com/MRCIEU/ieugwasr/issues/69#issuecomment-2085677808)

**Comment by JasonQiu** [comment]
`175.43.121.206` has been unblocked.

**Comment by angyi891349325** [comment]
I hope this message finds you. I am writing to express my sincerest apologies for submitting too many requests in a short period of time, causing your server to become overloaded recently. Initially, I was concerned that a potential network problem might prevent further connections, prompting me to send multiple queries in quick succession. Here is my ip address: 45.90.208.217. I hope you can help unblock it, thank you!

**Comment by JasonQiu** [comment]
> I hope this message finds you. I am writing to express my sincerest apologies for submitting too many requests in a short period of time, causing your server to become overloaded recently. Initially, I was concerned that a potential network problem might prevent further connections, prompting me to send multiple queries in quick succession. Here is my ip address: 45.90.208.217. I hope you can help unblock it, thank you!


The jail period should end at 2024-05-21 07:42:15 but I have unbanned the address manually now.

**Comment by 1233333333www** [comment]
help me 46.20.109.77

**Comment by 1233333333www** [comment]
Please help me!! I'm having the same issue. Could you unblock  ip address: 46.20.109.77? thank you!

**Comment by luckikiki000** [comment]
@JasonQiu I hope this message finds you. I am writing to express my sincerest apologies for our academic team submitting too many requests in a short period of time, causing your server to become overloaded recently. Our team has already learn the allowance rule and all of us think it makes the websites operating organized. We will try our best to avoid submitting too much data to cause excessive burden on your website. Here is our team members‘ ip address: 192.168.1.21 /192.168.1.22 /192.168.1.29 /192.168.1.30. I hope you can help unblock them, thank you!

**Comment by zcbucmedu** [comment]
> The jail period should end at 2024-05-21 07:42:15 but I have unbanned the address manually now.

Please help me!! I'm having the same issue. Could you unblock ip address: 10.112.10.84? thank you!

**Comment by ducktortan** [comment]
@JasonQiu I hope this message finds you. I am writing to express my sincerest apologies for our academic team submitting too many requests in a short period of time, causing your server to become overloaded recently. Our team has already learn the allowance rule and all of us think it makes the websites operating organized. We will try our best to avoid submitting too much data to cause excessive burden on your website. Here is our team members‘ ip address: 43.159.139.142 /115.197.42.93     I hope you can help unblock them, thank you!

**Comment by YF-93** [comment]
@JasonQiu I hope this message finds you well. I have similar problem, saying "The query to MR-Base exceeded 300 seconds and timed out.".  I am learning the MR analysis recently, and I also have difficulties on accessing this link: https://api.opengwas.io/profile/. It says, "Hmmm… can't reach this pageapi.opengwas.io took too long to respond."   Probably, it might due to my high frequency of request submission.  My ip address is: 175.159.180.68.  Sorry for the inconvenience! Thanks a lot!

**Comment by vestidor** [comment]
@JasonQiu I hope this message finds you. I am writing to express my sincerest apologies for submitting too many requests in a short period of time, causing your server to become overloaded recently. Initially, I was concerned that a potential network problem might prevent further connections, prompting me to send multiple queries in quick succession. Here is my ip address: 172.16.4.221. I hope you can help unblock it, thank you so much!

**Comment by Arteezyss** [comment]
I hope this message reaches you. I am writing to express my sincerest apologies for overloading your server with too many requests in a short period of time. Initially, I was concerned that potential network issues might prevent further connections, prompting me to rapidly send multiple queries. Here is my IP address: 172.27.201.187. I would greatly appreciate your assistance in unblocking it. Thank you very much!

**Comment by Fisheep00** [comment]
I hope this message finds you well. I am reaching out to express my sincere apologies for overwhelming your server by submitting an excessive number of requests in a brief period. As a consequence, my IP addresses, 170.106.76.96 and 170.106.177.143, have been affected. I kindly ask for your assistance in unblocking them. Thank you!
