### ISSUE TITLE
Error in api_query

### ISSUE THREAD

**Issue by pmquiros** [MRCIEU/ieugwasr#73]
I'm unable to connect to the API server; my connection is being refused. However, my user and token are functioning correctly since I can connect without any issues from my laptop. Could my IP be banned from the server?

```
> ieugwasr::api_status()
Error in api_query("status") : 
  The following error was encountered in trying to query the MR-Base server:
Error in curl::curl_fetch_memory(url, handle = handle): Failed to connect to api.opengwas.io port 443 after 43 ms: Connection refused
> ieugwasr::user()
Important note: do not share your token with others as it is equivalent to a password.
Error in api_query("user", opengwas_jwt = opengwas_jwt) : 
  The following error was encountered in trying to query the MR-Base server:
Error in curl::curl_fetch_memory(url, handle = handle): Failed to connect to api.opengwas.io port 443 after 43 ms: Connection refused
```

**Comment by pmquiros** [comment]
Dear Jason,
It still does not work. Could you please unblock my IP? 156.35.56.31

**Comment by JasonQiu** [comment]
The jail period should end at 2024-05-10 16:57:57 but I have unbanned the address manually now.

**Comment by pmquiros** [comment]
Thanks!

**Comment by GuohuaZhu** [comment]
I'm getting the same error. It has not yet been resolved.
```
> ieugwasr::api_status()
Error in api_query("status") : 
  The following error was encountered in trying to query the MR-Base server:
Error in curl::curl_fetch_memory(url, handle = handle): OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.opengwas.io:443 
```

**Comment by Zessi-C** [comment]
> The jail period should end at 2024-05-10 16:57:57 but I have unbanned the address manually now.

I aslo have similar problems, could you please kindly unban these IP 59.110.228.138 and 60.205.128.176?

Error message: The following error was encountered in trying to query the MR-Base server:
Error in curl::curl_fetch_memory(url, handle = handle): Failed to connect to api.opengwas.io port 443 after 175 ms: Couldn't connect to server

**Comment by clothohu** [comment]
I aslo have similar problems, could you please kindly unban these IP 192.168.31.41?
