### ISSUE TITLE
user() giving an error during the authentication step

### ISSUE THREAD

**Issue by Bhashitha2014** [MRCIEU/ieugwasr#77]
With the latest version 1.0.0, I am also getting the same error as mentioned below;
<img width="633" alt="Error_user()" src="https://github.com/MRCIEU/ieugwasr/assets/53751751/3b539366-d9fc-40c4-ae4f-58424ed61367">

I even tried to use the function "user(opengwas_jwt = get_opengwas_jwt())" as mentioned in the document (https://rdrr.io/github/MRCIEU/ieugwasr/man/user.html)

<img width="683" alt="error_get user details" src="https://github.com/MRCIEU/ieugwasr/assets/53751751/b3d1d54d-cf71-4cc2-99a3-8a2cf6e039d8">

Any help in this regard will be highly appreciated.

**Comment by neishaj** [comment]
You need a library like dplyr for the "%>%" operator to work. Loading that library would solve the error you got which said " could not find function "%>%" "

`install.packages("dplyr")`
`library(dplyr)`

**Comment by remlapmot** [comment]
@JasonQiu - this is actually a bug, which I've fixed in PR linked above.

Thanks for reporting this @Bhashitha2014. Loading dplyr or magrittr before running the code is the temporary work around code (that should not be necessary and isn't once PR merged).

**Comment by Bhashitha2014** [comment]
Thanks a lot @remlapmot  @JasonQiu. Now it's working :-)
