### ISSUE TITLE
Technical Support Request-Failed connect to api.opengwas.io:443; Connection refused

### ISSUE THREAD

**Issue by 15554136938** [MRCIEU/ieugwasr#78]
Sys.setenv(OPENGWAS_JWT="eyJhbGciOiJSUzI1NiIsImtpZCI6ImFwaS1qd3QiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJhcGkub3Blbmd3YXMuaW8iLCJhdWQiOiJhcGkub3Blbmd3YXMuaW8iLCJzdWIiOiIxNTU1NDEzNjkzOEAxNjMuY29tIiwiaWF0IjoxNzE4MDcxMjI2LCJleHAiOjE3MTkyODA4MjZ9.dc6O0mG95I3alxXI2SWG18z-PDitaCJFpKwow72b7v4PFTBzgO3oOMBEQWP7ArNqJw9Wru-TIbxBzFwcerdA2cXus6ItZAeuifa7msHGN1zgjuVVjoi9UdqpWhckdjVW6KK3FJlQm7Hth4YiXk966b5oEhFDZlGbNh6oXksa2lNgjNksIKgwGq0KALPQbNzTwJGJDmShoZJrk1xJUIGr_xD5Q_fUFVH-r_4h9qw-XThHwj7g6PNXotFNLn2s7wmeKvzVZ2XGm50hBafeudihOGOyPqci41r0CcAFSyTbP3Ad-VDp_sWcxYlWGIIa6tAPFQS1vS_n4OiJWU0i1kR_ig")

outcomes <- available_outcomes() Error in api_query("gwasinfo", opengwas_jwt = opengwas_jwt) :    
The following error was encountered in trying to query the MR-Base server: Error in curl::curl_fetch_memory(url, handle = handle): Failed connect to api.opengwas.io:443; Connection refused

Hello, this prompt appeared when I was running the API request. I can't use the API request to obtain data now. My IP address is 222.194.63.71. I am very sorry to bother you. Can you unblock this IP? I will strictly abide by the rules in my future research.

**Comment by JasonQiu** [comment]
Will be unbanned at 2024-06-17 12:21:39 GMT

**Comment by hqy823** [comment]
> ieugwasr::get_opengwas_jwt()
[1] "eyJhbGciOiJSUzI1NiIsImtpZCI6ImFwaS1qd3QiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJhcGkub3Blbmd3YXMuaW8iLCJhdWQiOiJhcGkub3Blbmd3YXMuaW8iLCJzdWIiOiIxNDQzNDc5ODAwQHFxLmNvbSIsImlhdCI6MTcxODg4NTA3OSwiZXhwIjoxNzIwMDk0Njc5fQ.RP-GwDa0MJSEz55rPGbYqidNQbZR23klyU4WGQrPGLU6oxPVcKXw7iBZil-qHmrvKp_l_nOP7-AEZebguiQu-MpREV-pvn0PQSaDOBH5UFUixuo_7y2kzn0-bUbaH_oa5jXDbA3RT1AbSJd6Y2YbObkRJ18dHIrigvHcptkWRxhAPLgCYw1SK3QXMrgyqiIi16FF-rnI_NbzthliV3JWJm-KxKjqe7AIEEmJEvHW_kXJ3p3CK7dFFIKxn_3q9p2_RoEyBRPP9ctx9oPPqbnwalFZh60dwMfxNfUgYZPRSim6KBc6Es87SA7l5VIgzqErzPasYp64iHmzgyYLsqYkVg"
> api_status()
Error in api_query("status") : 
  The following error was encountered in trying to query the MR-Base server:
Error in curl::curl_fetch_memory(url, handle = handle): Failed to connect to api.opengwas.io port 443: Connection refused
Hello, this prompt appeared when I was running the API request. I can't use the API request to obtain data now. My IP address is 114.236.141.194. I am very sorry to bother you. Can you unblock this IP? I will strictly abide by the rules in my future research.
