### ISSUE TITLE
Issue for "The query to MR-Base exceeded 300 seconds and timed out. Please simplify the query"

### ISSUE THREAD

**Issue by erkangYi** [MRCIEU/ieugwasr#85]
I hope this message finds you. I am writing to express my sincerest apologies for our academic team submitting too many requests in a short period of time, causing your server to become overloaded recently. Our team has already learn the allowance rule and all of us think it makes the websites operating organized. We will try our best to avoid submitting too much data to cause excessive burden on your website. Here is our team members‘ ip address: 192.168.1.4. I tried and I'm still banned. I hope you can help unblock them, thank you very much for your help!

**Comment by szkgg** [comment]
Dear jasonQiu,
I hope this message finds you well. I am writing to sincerely apologize for our academic team submitting too many requests in a short period of time, which has recently caused your server to become overloaded. Our team has already learned about the usage rules, and we all believe this helps maintain the organized operation of your website. We will do our best to avoid submitting excessive data to prevent overburdening your website.

Our team’s IP address is 192.168.1.4. After the last submission error, we were only able to connect to the IEU GWAS data for 2 minutes, and then we consistently received the message “The query to MR-Base exceeded 300 seconds and timed out.” I kindly request your assistance in resolving this issue. We greatly appreciate your help!

**Comment by szkgg** [comment]
Dear jasonQiu,
I hope this message finds you well. I am writing to sincerely apologize for our academic team submitting too many requests in a short period of time, which has recently caused your server to become overloaded. Our team has already learned about the usage rules, and we all believe this helps maintain the organized operation of your website. We will do our best to avoid submitting excessive data to prevent overburdening your website.

Our team’s IP address is 1192.168.10.192. After the last submission error, we were only able to connect to the IEU GWAS data for 2 minutes, and then we consistently received the message “The query to MR-Base exceeded 300 seconds and timed out.” I kindly request your assistance in resolving this issue. We greatly appreciate your help!

**Comment by szkgg** [comment]
Dear jasonQiu,
I hope this message finds you well. I am writing to sincerely apologize for our academic team submitting too many requests in a short period of time, which has recently caused your server to become overloaded. Our team has already learned about the usage rules, and we all believe this helps maintain the organized operation of your website. We will do our best to avoid submitting excessive data to prevent overburdening your website.

Our team’s IP address is 192.168.10.192. After the last submission error, we were only able to connect to the IEU GWAS data for 2 minutes, and then we consistently received the message “The query to MR-Base exceeded 300 seconds and timed out.” I kindly request your assistance in resolving this issue. We greatly appreciate your help!
