### ISSUE TITLE
Getting an error, unused argument(access_token = access_token) while trying to fetch data from MRCIEU db

### ISSUE THREAD

**Issue by Bhashitha2014** [MRCIEU/ieugwasr#89]
<img width="758" alt="Error_token" src="https://github.com/MRCIEU/ieugwasr/assets/53751751/becd42e0-10ea-4737-9a11-cdb068b86f33">

As mentioned above, I am getting an error, **unused argument(access_token = access_token)** while trying to fetch data from MRCIEU db after the authentication step was successful.

Any help in this regard will be highly appreciated.

Thanks!

**Comment by chengzhiang** [comment]
i try the different versions of TwosampleMR and ieugwasr, and the TwosampleMR(0.5.11) and ieugwasr(0.2.1) could work. u can try it.

**Comment by Bhashitha2014** [comment]
> i try the different versions of TwosampleMR and ieugwasr, and the TwosampleMR(0.5.11) and ieugwasr(0.2.1) could work. u can try it.

Thanks for letting me know. I am using the latest version of ieugwasr (1.0.0), and TwosampleMR(0.5.11). Any help with the latest version of ieugwasr (1.0.0)?

**Comment by JasonQiu** [comment]
Should try the latest versions of ieugwasr **and** TwoSampleMR

**Comment by el-rs** [comment]
> Should try the latest versions of ieugwasr **and** TwoSampleMR

Facing the same issue, while using latest version of both packages. Could there be any other criteria that needs to be checked?

**Comment by JasonQiu** [comment]
> > Should try the latest versions of ieugwasr **and** TwoSampleMR
> 
> Facing the same issue, while using latest version of both packages. Could there be any other criteria that needs to be checked?

@el-rs Please provide a full, minimal and reproducible example (minimal input and minimal code that can help us reproduce the entire error in a fresh R session)

**Comment by el-rs** [comment]
> > > Should try the latest versions of ieugwasr **and** TwoSampleMR
> > 
> > 
> > Facing the same issue, while using latest version of both packages. Could there be any other criteria that needs to be checked?
> 
> @el-rs Please provide a full, minimal and reproducible example (minimal input and minimal code that can help us reproduce the entire error in a fresh R session)

I'm calling a function from TwoSampleMR, which is using the ieugwasr::association() at the backend. Here's a sample reproducible snippet:

TwoSampleMR::extract_outcome_data(snps = "rs337148", outcomes = "ukb-a-248", proxies=TRUE)

Error message:
Error in ieugwasr::associations(variants = snps, id = outcomes, proxies = proxies,  : 
  unused argument (access_token = access_token)

I'm able to directly use the ieugwasr::associations() function without any issue.

**Comment by Bhashitha2014** [comment]
> Should try the latest versions of ieugwasr **and** TwoSampleMR

I am still facing the issue even after updating the ieugwasr and TwoSampleMR packages.

<img width="550" alt="image" src="https://github.com/user-attachments/assets/5a9e2ec8-d9b9-4f29-a5be-faf1ed87d8af">

Any help in this regard will be greatly appreciated.
