### ISSUE TITLE
Getting an error in authentication

### ISSUE THREAD

**Issue by 16090745lai** [MRCIEU/ieugwasr#91]
> exp<-extract_instruments(outcomes= c("ebi-a-GCST90018890"),p1 =5e-08)
Requesting default values. Extracting from pre-clumped data
0 out of 1 requested outcomes have pre-calculated instruments. 
Extracting data from 1 GWAS(s)
and performing LD clumping
 [>] 1 of 1
2024-06-26 20:40:10.761247> No httr_oauth_cache file found at mrbase.oauth - creating new file.
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [accounts.google.com] Failed to connect to accounts.google.com port 443 after 10001 ms: Timeout was reached

My token is is still valid, but when I run the extract line, my Chrome opens a Google OAuth page for me, and after I finish the authentication return to R, and that's the "timeout" error message.

**Comment by JasonQiu** [comment]
Check out the latest version of ieugwasr.
