### ISSUE TITLE
opengwas API error - IP address banned

### ISSUE THREAD

**Issue by szkgg** [MRCIEU/ieugwasr#96]
Hello, I had sent a few request to the opengwas API that inadvertently included many more variants than intended and it seems that my IP is now banned. Here is my IP address: 120.235.231.179. Could you please un-ban this IP address? We have solved the underlying issue and have fixed our files to have a much more reasonable list of interest. Apologies for overloading the server! Here is the error I got:
Using access token. For info on how this is used see logging_info()
ℹ 2024-07-10 08:51:36 > Setting client.id from options(googleAuthR.client_id)
ℹ The googleAuthR package is using a cached token for erkangyi1992@gmail.com.
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [oauth2.googleapis.com] Failed to connect to oauth2.googleapis.com port 443 after 9386 ms: Timed out
Using access token. For info on how this is used see logging_info()

**Comment by JasonQiu** [comment]
https://github.com/MRCIEU/ieugwasr/releases
https://cran.r-project.org/web/packages/ieugwasr/index.html
