### ISSUE TITLE
Abnormal waiting time when clumping...

### ISSUE THREAD

**Issue by sisihan96** [MRCIEU/ieugwasr#97]
Since last week i found that it took longer time when doing clumping...i updates the packages but still doesn't work..

**Comment by JasonQiu** [comment]
Please provide full, reproducible examples

**Comment by JasonQiu** [comment]
Please provide full, reproducible examples - what is in `INSULIN`?

Also please provide you IP address which can be found here https://whatismyipaddress.com/

**Comment by sisihan96** [comment]
> Please provide full, reproducible examples - what is in `INSULIN`?
> 
> Also please provide you IP address which can be found here https://whatismyipaddress.com/

-About INSULIN, the dataset is like:
![Screenshot 2024-07-15 at 10 22 05](https://github.com/user-attachments/assets/cc123f2c-9440-4c40-9fb6-67ecd2096da5)

-Which is formatted according to the following codes:
![Screenshot 2024-07-15 at 10 22 35](https://github.com/user-attachments/assets/5ff90421-7096-4777-948a-683e73845ae5)

-Here is the packages i loaded:
![Screenshot 2024-07-15 at 10 26 48](https://github.com/user-attachments/assets/299e6a34-06dd-498c-bcce-821dffb6af87)

-My IP: 
IPv4: ? [143.121.239.137](https://whatismyipaddress.com/ip/143.121.239.137)

Thank you!

**Comment by JasonQiu** [comment]
Please **_detach_** ieugwasr and TwoSampleMR,  **_remove_** them and install the latest versions:
```
install.packages("remotes")
remotes::install_github("mrcieu/ieugwasr")
remotes::install_github("MRCIEU/TwoSampleMR")
```

Also `gwas-api.mrcieu.ac.uk` will be decommissioned at any time. There is no need to specify the server using `options()`. Just use the latest versions of ieugwasr and it will select the up-to-date server by default.

**Comment by sisihan96** [comment]
> Please **_detach_** ieugwasr and TwoSampleMR, **_remove_** them and install the latest versions:
> 
> ```
> install.packages("remotes")
> remotes::install_github("mrcieu/ieugwasr")
> remotes::install_github("MRCIEU/TwoSampleMR")
> ```
> 
> Also `gwas-api.mrcieu.ac.uk` will be decommissioned at any time. There is no need to specify the server using `options()`. Just use the latest versions of ieugwasr and it will select the up-to-date server by default.

I reinstalled as you guided:
![Screenshot 2024-07-15 at 11 07 40](https://github.com/user-attachments/assets/927d7594-2222-445f-8745-7408b3a89f5c)
and encountered this issue:
![Screenshot 2024-07-15 at 11 08 26](https://github.com/user-attachments/assets/3db36bd1-5f32-48c8-807e-b64d920914a1)
I leaned it from another discussion that run 'options()' to solve this issue. 
After running 'options()' it shows the same issue as before:
![Screenshot 2024-07-15 at 11 11 52](https://github.com/user-attachments/assets/5abd365b-d660-4d7c-b670-d4cf6798afd6)

**Comment by JasonQiu** [comment]
Could you please upload your `Insulin.xlsx` as an attachment? There are still missing columns in the screenshot. We only need a minimal version - feel free to delete some rows and only include a few that will trigger the mtfrm error.

**Comment by sisihan96** [comment]
> Could you please upload your `Insulin.xlsx` as an attachment? There are still missing columns in the screenshot. We only need a minimal version - feel free to delete some rows and only include a few that will trigger the mtfrm error.

Hi Jason,
here is the file for your kind check.
[INSULIN_test.xlsx](https://github.com/user-attachments/files/16233034/INSULIN_test.xlsx)

**Comment by JasonQiu** [comment]
I couldn't reproduce the error. Did I miss something?

```
> View(INSULIN)
> exposure_ins <- clump_data(INSULIN, clump_p1 = 1, clump_p2 = 1, clump_kb = 1000, clump_r2 = 0.1, pop = "EUR")
pval.exposure not present, setting clumping p-value to 0.99 for all variants
Please look at vignettes for options on running this locally if you need to run many instances of this command.
Clumping rZSgpq, 39 variants, using EUR population reference
Removing 28 of 39 variants due to LD with other variants or absence from LD reference panel
> View(exposure_ins)
```

![image](https://github.com/user-attachments/assets/7220dcef-8911-4407-bce5-2f9f088c068c)


![image](https://github.com/user-attachments/assets/5c751ade-374a-4ade-b43f-8f8fcf25ee5e)


```
> print(sessionInfo())
R version 4.2.3 (2023-03-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS 14.5

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readxl_1.4.3      TwoSampleMR_0.6.6 ieugwasr_1.0.1   

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.12       rstudioapi_0.14   magrittr_2.0.3    tidyselect_1.2.1  R6_2.5.1         
 [6] rlang_1.1.4       fansi_1.0.6       httr_1.4.7        plyr_1.8.9        dplyr_1.1.4      
[11] tools_4.2.3       data.table_1.15.4 utf8_1.2.4        cli_3.6.3         tibble_3.2.1     
[16] lifecycle_1.0.4   vctrs_0.6.5       curl_5.2.1        glue_1.7.0        compiler_4.2.3   
[21] pillar_1.9.0      cellranger_1.1.0  generics_0.1.3    jsonlite_1.8.8    pkgconfig_2.0.3  
```

**Comment by sisihan96** [comment]
> I couldn't reproduce the error. Did I miss something?
> 
> ```
> > View(INSULIN)
> > exposure_ins <- clump_data(INSULIN, clump_p1 = 1, clump_p2 = 1, clump_kb = 1000, clump_r2 = 0.1, pop = "EUR")
> pval.exposure not present, setting clumping p-value to 0.99 for all variants
> Please look at vignettes for options on running this locally if you need to run many instances of this command.
> Clumping rZSgpq, 39 variants, using EUR population reference
> Removing 28 of 39 variants due to LD with other variants or absence from LD reference panel
> > View(exposure_ins)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/22163445/348670535-7220dcef-8911-4407-bce5-2f9f088c068c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzkyNjMsIm5iZiI6MTcyMTAzODk2MywicGF0aCI6Ii8yMjE2MzQ0NS8zNDg2NzA1MzUtNzIyMGRjZWYtODkxMS00NDA3LWJjZTUtMmY5ZjA4OGMwNjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEwMjI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYTUyNjk0YzMyMThjNzdjMWUzYjE5ZmRhODE3YWRiZTE1Zjk0NTA1OTk1MDBiNjhiNzZhMDg1YWRmMTQzOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Opwc2D4G0YbaeC64cdTsp0ptMt2msypCq66kUlxeNjA)
> 
> ![image](https://private-user-images.githubusercontent.com/22163445/348671202-5c751ade-374a-4ade-b43f-8f8fcf25ee5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzkyNjMsIm5iZiI6MTcyMTAzODk2MywicGF0aCI6Ii8yMjE2MzQ0NS8zNDg2NzEyMDItNWM3NTFhZGUtMzc0YS00YWRlLWI0M2YtOGY4ZmNmMjVlZTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEwMjI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNmY3YTdjY2Q4ZDQ0MmIzNTU2MjY3N2I1YWJiNmYzYTIzMmExNWVmNDE2NjYzZjM0MTNkOTVjZDNjOWJiNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ExQULUGwXtgSFiw21DhX7ZO-qw5KADMy4lqcQ0naPN8)
> 
> ```
> > print(sessionInfo())
> R version 4.2.3 (2023-03-15)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS 14.5
> 
> Matrix products: default
> LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] readxl_1.4.3      TwoSampleMR_0.6.6 ieugwasr_1.0.1   
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.12       rstudioapi_0.14   magrittr_2.0.3    tidyselect_1.2.1  R6_2.5.1         
>  [6] rlang_1.1.4       fansi_1.0.6       httr_1.4.7        plyr_1.8.9        dplyr_1.1.4      
> [11] tools_4.2.3       data.table_1.15.4 utf8_1.2.4        cli_3.6.3         tibble_3.2.1     
> [16] lifecycle_1.0.4   vctrs_0.6.5       curl_5.2.1        glue_1.7.0        compiler_4.2.3   
> [21] pillar_1.9.0      cellranger_1.1.0  generics_0.1.3    jsonlite_1.8.8    pkgconfig_2.0.3  
> ```

That is so weird...i used the file i sent you but still cannot get the output, we have the same process, is it because of the part 'loaded via a namespace'?
![Screenshot 2024-07-15 at 13 01 51](https://github.com/user-attachments/assets/43559864-dde2-4309-bd63-dcd0487fa85c)

**Comment by JasonQiu** [comment]
Unlikely.

Could you try this:

```
> detach("package:TwoSampleMR", unload = TRUE)
> detach("package:ieugwasr", unload = TRUE)
> options("ieugwasr_api")
$ieugwasr_api
[1] "https://api.opengwas.io/api/"
```

If you get the same output (`[1] "https://api.opengwas.io/api/"`), proceed. Otherwise run `ieugwasr::select_api()` and check the options output again. **_DO NOT_** use gwas-api.mrcieu.ac.uk anymore.

Then run `ieugwasr::user()`. If you can see your user information, proceed. Otherwise follow https://mrcieu.github.io/ieugwasr/articles/guide.html#authentication, until ieugwasr::user() returns your user info. Note: do not post the response here as it contains your personal data.

Finally run the following and see what do you have:

```
> library(readxl)
> dataMR_3 <- read_excel("~/Desktop/INSULIN_test.xlsx")
> INSULIN = format_data(dataMR_3, type = "exposure", snp_col = "SNP", beta_col = "Beta", se_col = "SE", effect_allele_col = "EA", other_allele_col = "NEA", eaf_col = "EAF", pval_col = "P", gene_col = "Gene", chr_col = "CHR", pos_col = "POS", samplesize_col = "N")
> exp <- clump_data(INSULIN, clump_p1 = 1, clump_p2 = 1, clump_kb = 1000, clump_r2 = 0.1, pop = "EUR")
```

**Comment by sisihan96** [comment]
> Unlikely.
> 
> Could you try this:
> 
> ```
> > detach("package:TwoSampleMR", unload = TRUE)
> > detach("package:ieugwasr", unload = TRUE)
> > options("ieugwasr_api")
> $ieugwasr_api
> [1] "https://api.opengwas.io/api/"
> ```
> 
> If you get the same output (`[1] "https://api.opengwas.io/api/"`), proceed. Otherwise run `ieugwasr::select_api()` and check the options output again. **_DO NOT_** use gwas-api.mrcieu.ac.uk anymore.
> 
> Then run `ieugwasr::user()`. If you can see your user information, proceed. Otherwise follow https://mrcieu.github.io/ieugwasr/articles/guide.html#authentication, until ieugwasr::user() returns your user info. Note: do not post the response here as it contains your personal data.
> 
> Finally run the following and see what do you have:
> 
> ```
> > library(readxl)
> > dataMR_3 <- read_excel("~/Desktop/INSULIN_test.xlsx")
> > INSULIN = format_data(dataMR_3, type = "exposure", snp_col = "SNP", beta_col = "Beta", se_col = "SE", effect_allele_col = "EA", other_allele_col = "NEA", eaf_col = "EAF", pval_col = "P", gene_col = "Gene", chr_col = "CHR", pos_col = "POS", samplesize_col = "N")
> > exp <- clump_data(INSULIN, clump_p1 = 1, clump_p2 = 1, clump_kb = 1000, clump_r2 = 0.1, pop = "EUR")
> ```

It works now!! Thank you so much Jason. The problem arises from the different token in .Renviron. Everything goes smoothly after I change it. 
Really appreciate your patient help:)
