### ISSUE TITLE
Using the new API but still cannot do ld_clump

### ISSUE THREAD

**Issue by naesilla** [MRCIEU/ieugwasr#98]
Hello.

The message has persisted for the last three days.
Server code: 502; Server is possibly experiencing traffic, trying again...
Server code: 502; Server is possibly experiencing traffic, trying again...
Server code: 502; Server is possibly experiencing traffic, trying again...
Server code: 502; Server is possibly experiencing traffic, trying again...
Server code: 502; Server is possibly experiencing traffic, trying again...
Server code: 502; Server is possibly experiencing traffic, trying again...
Server error: 502
Failed to retrieve results from server. See error status message in the returned object and contact the developers if the problem persists.
Error in mtfrm.default(list(url = "http://gwas-api.mrcieu.ac.uk/ld/clump",  : 
  cannot mtfrm
  
Is this only me? 
How do I solve this problem?

Thank you.

Edit: I have changed the API to the new one (token is good, already make sure of that.

Now the error message is
Please look at vignettes for options on running this locally if you need to run many instances of this command.
Clumping ZY8lSN, 21029 variants, using EUR population reference
No encoding supplied: defaulting to UTF-8.
Error in mtfrm.default(list(url = "https://api.opengwas.io/api/ld/clump",  : 
  cannot mtfrm
In addition: Warning message:
In set_reset(r) :
  You have used up your OpenGWAS allowance. Your allowance will reset at 2024-07-22 14:17:50.191798. See https://api.opengwas.io/api/#allowance for more details.
  
 and I ran out of token everytime. What should I do?

**Comment by Gong21** [comment]
I have the same problem too, when using the new API (https://api.opengwas.io/api/), even after my token is authenticated. When I ran ieugwasr::ld_clump, either all of the variants were removed, or I received this error "Error in mtfrm.default(list(url = "http://gwas-api.mrcieu.ac.uk/ld/clump", : cannot mtfrm". How can I fix this?

**Comment by naesilla** [comment]
I noticed, the ld_clump may work when we have less than 40.000 SNPs at one clump, and always recheck your tokens.
However, at the end, I just used ld_clump_local, using plink, by downloading the reference panel. It is much more easier to do.
